# Generated by Django 3.0.1 on 2020-02-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Null', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
